"""Software / infrastructure engineering agents.

ArchitectAgent  -> turns a spec into a concrete file plan (JSON).
CodeWriterAgent -> writes the real contents of one file, in context.

These power the app builder so you can say "build me the backend of X" and get
an actual project on disk, generated by your local code model.
"""

from __future__ import annotations

import json
import re
from typing import Any, Dict, List, Optional

from aether.agents.base import AgentResult, BaseAgent

ARCHITECT_SYSTEM = """You are a principal software architect.
Given a build request, design a concrete, minimal-but-complete project.
Reply ONLY with compact JSON, no markdown:
{
  "project_name": "kebab-case-name",
  "summary": "one sentence",
  "stack": ["language", "framework", "db", ...],
  "run_command": "how to start it locally",
  "install_command": "how to install deps locally",
  "files": [
    {"path": "relative/path.ext", "purpose": "short purpose"}
  ]
}
Rules:
- Keep it LOCAL-first (SQLite over hosted DB, no paid cloud services).
- 5-20 files. Include README.md, dependency manifest, entrypoint, and config.
- Order files so foundational ones come first.
- Prefer well-known stacks (FastAPI/Flask/Express/React/Vite) unless told otherwise."""

CODER_SYSTEM = """You are a senior engineer writing one file of a larger project.
Output ONLY the raw file contents. No markdown fences, no commentary.
Write complete, working, idiomatic code consistent with the stack and the other files.
Include reasonable error handling. Do not leave TODO stubs in critical paths."""


class ArchitectAgent(BaseAgent):
    role_name = "architect"

    def execute(self, input_data: Dict[str, Any]) -> AgentResult:
        spec = input_data.get("spec", input_data.get("project_description", ""))
        constraints = input_data.get("constraints", "")
        user = (
            f"BUILD REQUEST:\n{spec}\n\n"
            f"CONSTRAINTS:\n{constraints or 'local-first, runnable on a laptop'}\n\n"
            "Design the project."
        )
        raw = self._llm(user)
        plan = _parse_json(raw) or _fallback_plan(spec)
        plan.setdefault("files", [])
        return self._ok(plan)

    def _llm(self, user: str) -> str:
        if not self.llm:
            return ""
        # Architecture is reasoning-heavy -> general/plan model.
        if hasattr(self.llm, "complete"):
            try:
                return self.llm.complete(user, system=ARCHITECT_SYSTEM, task="plan")
            except TypeError:
                return self.llm.complete(user, system=ARCHITECT_SYSTEM)
        return ""


class CodeWriterAgent(BaseAgent):
    role_name = "code_writer"

    def execute(self, input_data: Dict[str, Any]) -> AgentResult:
        plan = input_data.get("plan", {})
        file_path = input_data.get("file_path", "")
        purpose = input_data.get("purpose", "")
        manifest = input_data.get("manifest", "")
        user = (
            f"PROJECT: {plan.get('project_name', 'app')}: {plan.get('summary', '')}\n"
            f"STACK: {', '.join(plan.get('stack', []))}\n"
            f"ALL FILES: {manifest}\n\n"
            f"NOW WRITE THIS FILE: {file_path}\n"
            f"PURPOSE: {purpose}\n\n"
            "Output the full contents of this file only."
        )
        content = self._llm(user)
        return self._ok({"path": file_path, "content": _strip_fences(content)})

    def _llm(self, user: str) -> str:
        if not self.llm:
            return ""
        if hasattr(self.llm, "complete"):
            try:
                return self.llm.complete(user, system=CODER_SYSTEM, task="code")
            except TypeError:
                return self.llm.complete(user, system=CODER_SYSTEM)
        return ""


def _parse_json(raw: str) -> Optional[Dict[str, Any]]:
    if not raw:
        return None
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        return None
    try:
        return json.loads(match.group(0))
    except json.JSONDecodeError:
        return None


def _strip_fences(text: str) -> str:
    if not text:
        return ""
    fence = re.match(r"^\s*```[\w.-]*\n(.*)\n```\s*$", text, re.DOTALL)
    if fence:
        return fence.group(1)
    return text


def _fallback_plan(spec: str) -> Dict[str, Any]:
    return {
        "project_name": "app",
        "summary": spec[:120],
        "stack": ["python", "fastapi"],
        "run_command": "uvicorn main:app --reload",
        "install_command": "pip install -r requirements.txt",
        "files": [
            {"path": "README.md", "purpose": "overview and run steps"},
            {"path": "requirements.txt", "purpose": "dependencies"},
            {"path": "main.py", "purpose": "application entrypoint"},
        ],
    }
